name: webtrit_callkeep_platform_interface
description: A common platform interface for the webtrit_callkeep plugin.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0
  equatable: ^2.0.5
  dart_casing: ^2.0.0
  build_runner: ^2.4.4
  source_gen: ^1.3.2
  build: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  mockito: ^5.4.1
  path: ^1.8.3
