name: webtrit_callkeep_platform_interface
description: A common platform interface for the webtrit_callkeep plugin.
version: 0.3.5+0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  equatable: ^2.0.7
  dart_casing: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^7.4.5
  very_good_analysis: ^7.0.0
  mockito: ^5.4.5
  build_runner: ^2.4.15
