include: package:very_good_analysis/analysis_options.5.1.0.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.pigeon.dart"

linter:
  rules:
    lines_longer_than_80_chars: false # Conflicts with the team's preference