name: webtrit_callkeep_example
description: Demonstrates how to use the callkeep plugin.
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  webtrit_callkeep:
    path: ../
  permission_handler: ^11.4.0
  path_provider: ^2.1.5
  go_router: ^14.8.1
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  clock: ^1.1.2
  logging: ^1.3.0
  logging_appenders: ^1.3.1
  fluttertoast: ^8.2.12

flutter:
  uses-material-design: true
