name: webtrit_callkeep_example
description: Demonstrates how to use the callkeep plugin.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  webtrit_callkeep:
    path: ../
  permission_handler: ^11.3.1
  path_provider: ^2.1.0
  go_router: ^14.3.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  hydrated_bloc: ^9.1.5
  clock: ^1.1.1

flutter:
  uses-material-design: true
