name: webtrit_callkeep_example
description: Demonstrates how to use the callkeep plugin.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  webtrit_callkeep:
    path: ../

  cupertino_icons: ^1.0.5
  firebase_core: ^2.13.0
  firebase_messaging: ^14.6.1
  logging: ^1.2.0
  shared_preferences: ^2.1.1
  path_provider: ^2.0.15
  uuid: ^4.2.2
  go_router: ^7.1.1

  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.1

  meta: ^1.9.1
  clock: ^1.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
