name: webtrit_callkeep_ios
description: iOS implementation of the webtrit_callkeep plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  plugin:
    implements: webtrit_callkeep
    platforms:
      ios:
        pluginClass: WebtritCallkeepPlugin
        dartPluginClass: WebtritCallkeep

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.2.2
  webtrit_callkeep_platform_interface:
    path: ../webtrit_callkeep_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  pigeon: ^16.0.5
  very_good_analysis: ^5.1.0
